#pragma once

#include "NativeGameplayTags.h"

namespace ANPGameplayTags
{

	ANEWPERSPECTIVE_API		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Move);
	ANEWPERSPECTIVE_API		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Jump);
	ANEWPERSPECTIVE_API		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Dash);
	ANEWPERSPECTIVE_API		UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Switch);

}